Description: "E-Health Workshop Stack"
Parameters:
  NotebookInstanceType:
    Type: String
    Default: "t2.micro"
  NotebookInstanceImage:
    Type: AWS::EC2::Image::Id
    Default: "ami-cb9ec1b1"
  NotebookInstanceKeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  NotebookRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns: 
        - 
          "arn:aws:iam::aws:policy/PowerUserAccess"
  NotebookInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles: 
        - 
          !Ref "NotebookRole"
  NotebookInstance:
    Type: "AWS::EC2::Instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
    Properties:
      KeyName: !Ref NotebookInstanceKeyName
      InstanceType: !Ref NotebookInstanceType
      ImageId: !Ref NotebookInstanceImage
      IamInstanceProfile: !Ref NotebookInstanceProfile 
      SecurityGroups:
        - Ref: "InstanceSecurityGroup"
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex"
              - "\n"
              - "yum install -y git aws-cfn-bootstrap \n"
              - "cd /usr/src \n"
              - "git clone https://github.com/InternetOfHealthcare/ehealth-workshop.git \n"
              - "cd ehealth-workshop \n"
              - "source ./ehw_notebook_userdata.sh \n"
              - "\n"
              - "/opt/aws/bin/cfn-signal -e $? "
              - " --stack "
              - !Ref AWS::StackName
              - " --resource NotebookInstance "
              - " --region "
              - !Ref AWS::Region
              - "\n"

  # We're allowing any ip address to access port 22 and 3000
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTPD on 80 and Jupyter on port 8888"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"      
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"      
        - IpProtocol: "tcp"
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: "0.0.0.0/0"

Outputs:
  NotebookURL:
    Description: "Notebook Instance URL"
    Value:
      Fn::Join:
        - ""
        -
          - "http://"
          - Fn::GetAtt:
              - "NotebookInstance"
              - "PublicIp"
          - "/notebooks/index.ipynb"

  NotebookPassword:
    Description: "Notebook Password"
    Value: "badwolf"