Description: "E-Health Workshop Stack"
Resources:
  NotebookInstance:
    Type: "AWS::EC2::Instance"
    CreationPolicy:
      ResourceSignal:
        Timeout: PT60M
    Properties:
      KeyName: debug_kp
      InstanceType: "t2.micro"
      ImageId: "ami-cb9ec1b1"
      SecurityGroups:
        - Ref: "InstanceSecurityGroup"
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -ex"
              - "\n"
              - "yum install -y git aws-cfn-bootstrap \n"
              - "cd /usr/src \n"
              - "git clone https://github.com/InternetOfHealthcare/ehealth-workshop.git \n"
              - "cd ehealth-workshop \n"
              - "source ./ehw_notebook_userdata.sh \n"
              - "\n"
              - "/opt/aws/bin/cfn-signal -e $? "
              - " --stack "
              - !Ref AWS::StackName
              - " --resource NotebookInstance "
              - " --region "
              - !Ref AWS::Region
              - "\n"

  # We're allowing any ip address to access port 22 and 3000
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTPD on 80 and Jupyter on port 8888"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"      
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"      
        - IpProtocol: "tcp"
          FromPort: "8888"
          ToPort: "8888"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "3000"
          ToPort: "3000"
          CidrIp: "0.0.0.0/0"

Outputs:
  WebsiteURL:
    Description: "Our Website URL"
    Value:
      Fn::Join:
        - ""
        -
          - "http://"
          - Fn::GetAtt:
              - "NotebookInstance"
              - "PublicIp"
          - ":80"